services:
    postgres:
        container_name: postgres-db
        image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres_db
        ports:
          - '16543:5432'
        volumes:    
          - postgres-data:/var/lib/postgresql/data
    pgadmin:
        container_name: test-db-manage
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'test@email.com'
            PGADMIN_DEFAULT_PASSWORD: 'test'
            # PGADMIN_CONFIG_SERVER_MODE: 'False'
            # PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
        ports:
            - 8080:80
        volumes:
            - ./docker/servers.json:/pgadmin4/servers.json
            - ./docker/pgpass:/pgpass
        depends_on:
          - "postgres"
            
volumes:
  postgres-data: